version: 0.1
Resources:
  - TargetService:
    Type: AWS::ECS::Service
    Properties:
    TaskDefinition: "arn:aws:ecs:ap-northeast-2:314757280827:task-definition/KorDevLocust:1"
    LoadBalancerInfo:
    ContainerName: "locust-master"
    ContainerPort: 8089
    PlatformVersion: "LATEST"
    NetworkConfiguration:
    AwsvpcConfiguration:
      Subnets: ["subnet-cafb32b1","subnet-5e8b4e37"]
      SecurityGroups:
      [
        sg-0f2120ab07402e01b,
      ]
    AssignPublicIp: "ENABLED"
